### ISSUE TITLE
Tuple does not suport

### ISSUE THREAD

**Issue by Satishvermatcs** [Opetushallitus/scala-schema#1]
Hi Team,
## In my case classes , tuple has been used , it looks like this is not supported in JsonSchemaGeneration utility.Below is the exception for your reference -----

Exception in thread "main" java.lang.RuntimeException: Unsupported type: T1
    at fi.oph.scalaschema.SchemaFactory$$anonfun$fi$oph$scalaschema$SchemaFactory$$createSchema$1.apply(SchemaFactory.scala:53)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$fi$oph$scalaschema$SchemaFactory$$createSchema$1.apply(SchemaFactory.scala:50)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:59)
    at fi.oph.scalaschema.SchemaFactory.fi$oph$scalaschema$SchemaFactory$$createSchema(SchemaFactory.scala:49)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$7.apply(SchemaFactory.scala:117)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$7.apply(SchemaFactory.scala:115)
    at scala.collection.immutable.List.map(List.scala:273)
    at fi.oph.scalaschema.SchemaFactory.createClassSchema(SchemaFactory.scala:115)
    at fi.oph.scalaschema.SchemaFactory.fi$oph$scalaschema$SchemaFactory$$createClassOrTraitSchema(SchemaFactory.scala:84)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$fi$oph$scalaschema$SchemaFactory$$createSchema$1.apply(SchemaFactory.scala:51)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$fi$oph$scalaschema$SchemaFactory$$createSchema$1.apply(SchemaFactory.scala:50)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:59)
    at fi.oph.scalaschema.SchemaFactory.fi$oph$scalaschema$SchemaFactory$$createSchema(SchemaFactory.scala:49)
    at fi.oph.scalaschema.SchemaFactory.fi$oph$scalaschema$SchemaFactory$$createSchema(SchemaFactory.scala:47)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$7.apply(SchemaFactory.scala:117)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$7.apply(SchemaFactory.scala:115)
    at scala.collection.immutable.List.map(List.scala:277)
    at fi.oph.scalaschema.SchemaFactory.createClassSchema(SchemaFactory.scala:115)
    at fi.oph.scalaschema.SchemaFactory.fi$oph$scalaschema$SchemaFactory$$createClassOrTraitSchema(SchemaFactory.scala:84)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$fi$oph$scalaschema$SchemaFactory$$createSchema$1.apply(SchemaFactory.scala:51)
    at fi.oph.scalaschema.SchemaFactory$$anonfun$fi$oph$scalaschema$SchemaFactory$$createSchema$1.apply(SchemaFactory.scala:50)
    at scala.collection.MapLike$class.getOrElse(MapLike.scala:128)
    at scala.collection.AbstractMap.getOrElse(Map.scala:59)
    at fi.oph.scalaschema.SchemaFactory.fi$oph$scalaschema$SchemaFactory$$createSchema(SchemaFactory.scala:49)
    at fi.oph.scalaschema.SchemaFactory.createSchema(SchemaFactory.scala:21)
    at fi.oph.scalaschema.SchemaFactory.createSchema(SchemaFactory.scala:25)
    at com.imshealth.JsonSchemaGenTest$.main(JsonSchemaGenTest.scala:25)
    at com.imshealth.JsonSchemaGenTest.main(JsonSchemaGenTest.scala)

**Comment by raimohanska** [comment]
Sorry I just noticed your Issue :(

What kind of JSON would you like your Tuple to map into? That's not at all obvious to me. I'd rather use a case class with named fields to make the JSON more readable.

I'm perfectly ok with adding tuple support though, if we can agree on how Tuples are to be represented in JSON.
